name: OktaMobileSDK

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

env:
  swift_package_resolve: swift package resolve
  swift_build: swift build --build-tests
  swift_test: swift test

jobs:
  macOS:
    strategy:
      fail-fast: false
      matrix:
        xcode: ["13.2.1", "13.1"]
        include:
          - xcode: "13.2.1"
            macos: macOS-11
          - xcode: "13.1"
            macos: macOS-11
    runs-on: ${{ matrix.macos }}
    name: macOS
    steps:
    - uses: actions/checkout@master
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app; swift -version
    - name: Get Swift Version
      id: get-swift-version
      run: |
          echo "::set-output name=version::$(swift -version | head -n 1 | sed s/,// )"
      shell: bash
    - name: Build
      run: ${{ env.swift_build }}
    - name: Test
      run: ${{ env.swift_test }}

  linux:
    strategy:
      fail-fast: false
      matrix:
        swift: ["5.5", "5.4"]
        include:
          - swift: "5.5"
            container: "swift:5.5"
          - swift: "5.4"
            container: "swift:5.4"
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    name: Linux
    steps:
    - name: Get Swift Version
      id: get-swift-version
      run: |
        echo "::set-output name=version::$(swift -version | head -n 1 | sed s/,// )"
      shell: bash
    - uses: actions/checkout@master
    - name: Build
      run: ${{ env.swift_build }} --enable-test-discovery
    - name: Test
      run: ${{ env.swift_test }} --enable-test-discovery
